AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  bustleit-backend-serverless

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - arm64
    Environment:
      Variables:
        DYNAMODB_TABLE: BustleIt-DB
        AWS_REGION: me-south-1

Resources:
  UserProfileFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: packages/userprofile-lambda
      Handler: bootstrap
      Role: !GetAtt UserProfileFunctionRole.Arn
      Events:
        GetUserProfile:
          Type: Api
          Properties:
            Path: /v1/user/profile/{id}
            Method: get
        GetUserProfiles:
          Type: Api
          Properties:
            Path: /v1/user/profiles
            Method: get
        GetUserProfilesBatch:
          Type: Api
          Properties:
            Path: /v1/user/profiles/batch
            Method: post

  UserTasksFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: packages/usertasks-lambda
      Handler: bootstrap
      Role: !GetAtt UserTasksFunctionRole.Arn
      Events:
        GetUserSchedule:
          Type: Api
          Properties:
            Path: /v1/user/{user_id}/schedule
            Method: get

  UserProfileFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/BustleItDynamoDBPolicy

  UserTasksFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/BustleItDynamoDBPolicy

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UserProfileFunctionArn:
    Description: "UserProfile Lambda Function ARN"
    Value: !GetAtt UserProfileFunction.Arn
  UserTasksFunctionArn:
    Description: "UserTasks Lambda Function ARN"
    Value: !GetAtt UserTasksFunction.Arn
