AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  bustleit-backend-serverless

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - arm64

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./crates/auth-lambda
      Handler: bootstrap
      Role: !GetAtt AuthFunctionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE: BustleIt-DB
          AWS_REGION: me-south-1
      Events:
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post

  AiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./crates/ai-lambda
      Handler: bootstrap
      Role: !GetAtt AiFunctionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE: BustleIt-DB
          AWS_REGION: me-south-1
      Events:
        UserData:
          Type: Api
          Properties:
            Path: /ai/request/userdata
            Method: post
        AllUsers:
          Type: Api
          Properties:
            Path: /ai/request/allusers
            Method: get
        ClusteredUsers:
          Type: Api
          Properties:
            Path: /ai/request/clusteredUsers
            Method: get
        Tasks:
          Type: Api
          Properties:
            Path: /ai/request/tasks
            Method: get
        TaskedUsers:
          Type: Api
          Properties:
            Path: /ai/request/taskedUsers
            Method: get
        Schedules:
          Type: Api
          Properties:
            Path: /ai/request/schedules
            Method: post

  RecommendFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./crates/recommend-lambda
      Handler: bootstrap
      Role: !GetAtt RecommendFunctionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE: BustleIt-DB
          AWS_REGION: me-south-1
      Events:
        Recommend:
          Type: Api
          Properties:
            Path: /recommend
            Method: post
        RecommendTest:
          Type: Api
          Properties:
            Path: /recommend/test
            Method: get

  # IAM Roles for Lambda Functions
  AuthFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/BustleItDynamoDBPolicy

  AiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/BustleItDynamoDBPolicy

  RecommendFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/BustleItDynamoDBPolicy

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AuthFunctionArn:
    Description: "Auth Lambda Function ARN"
    Value: !GetAtt AuthFunction.Arn
  AiFunctionArn:
    Description: "AI Lambda Function ARN"
    Value: !GetAtt AiFunction.Arn
  RecommendFunctionArn:
    Description: "Recommend Lambda Function ARN"
    Value: !GetAtt RecommendFunction.Arn
