AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  bustleit-backend-serverless

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - arm64

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./crates/auth-lambda
      Handler: bootstrap
      Events:
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post

  AiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./crates/ai-lambda
      Handler: bootstrap
      Events:
        UserData:
          Type: Api
          Properties:
            Path: /ai/request/userdata
            Method: post
        AllUsers:
          Type: Api
          Properties:
            Path: /ai/request/allusers
            Method: get
        ClusteredUsers:
          Type: Api
          Properties:
            Path: /ai/request/clusteredUsers
            Method: get
        Tasks:
          Type: Api
          Properties:
            Path: /ai/request/tasks
            Method: get
        TaskedUsers:
          Type: Api
          Properties:
            Path: /ai/request/taskedUsers
            Method: get
        Schedules:
          Type: Api
          Properties:
            Path: /ai/request/schedules
            Method: post

  RecommendFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./crates/recommend-lambda
      Handler: bootstrap
      Events:
        Recommend:
          Type: Api
          Properties:
            Path: /recommend
            Method: post
        RecommendTest:
          Type: Api
          Properties:
            Path: /recommend/test
            Method: get

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AuthFunctionArn:
    Description: "Auth Lambda Function ARN"
    Value: !GetAtt AuthFunction.Arn
  AiFunctionArn:
    Description: "AI Lambda Function ARN"
    Value: !GetAtt AiFunction.Arn
  RecommendFunctionArn:
    Description: "Recommend Lambda Function ARN"
    Value: !GetAtt RecommendFunction.Arn
  AuthFunctionRole:
    Description: "IAM Role created for Auth function"
    Value: !GetAtt AuthFunctionRole.Arn
  AiFunctionRole:
    Description: "IAM Role created for AI function"
    Value: !GetAtt AiFunctionRole.Arn
  RecommendFunctionRole:
    Description: "IAM Role created for Recommend function"
    Value: !GetAtt RecommendFunctionRole.Arn
